/*

 Ngine v5.0
 
 Module      : Effect 
 Requirements: none
 Description : Helper class combining different shader
               stages into complete pipeline program.

*/

#ifndef ENG_RESOURCES_EFFECT
#define ENG_RESOURCES_EFFECT

#include "core/rendering/pipeline.h"
#include "core/rendering/shader.h"

#include <map>
#include <vector>
using namespace std;

#if !defined(EN_PLATFORM_OSX)

using namespace en::gpu;

namespace en
{
   enum ShadingLanguage
        {
        eGLSL_1_10 = 0,
        eGLSL_1_20    ,
        eGLSL_1_30    ,
        eGLSL_1_40    ,
        eGLSL_1_50    ,
        eGLSL_3_30    ,
        eGLSL_4_00    ,
        eGLSL_4_10    ,
        eGLSL_4_20    ,
        eGLSL_4_30    ,
        eGLSL_4_40    ,
        eGLSL_4_50    ,
        eESSL_1_00    ,
        eESSL_3_00    ,
        ShadingLanguageVersionsCount
        };

   // Parameters common for whole scene/frame
   aligned(1) 
   struct SceneParameters
      {
      float4x4 camViewProjection[2];
      float4x4 camProjection[2];
      float4x4 camView[2];
      sint32   instances;   // packed0
      sint32   stereo;
      sint32   res_0;
      sint32   res_1;
      };
   aligndefault

   class Effect
         {
         private:
         string         shader[underlyingType(ShaderStage::Count)]; // Shaders code for each stage
         vector<string> code[underlyingType(ShaderStage::Count)];   // Preprocessor code autogenerated for each stage
         shared_ptr<Pipeline>  binary;                      // Compiled and linked pipeline
         bool           dirty;                       // Do we need to recompile?
   
         public:
			 Effect(ShadingLanguage version, string name);
        ~Effect();
   
         void attach(ShaderStage stage, string code); // Add code to given shader stage
         bool stage(ShaderStage stage);               // Checks if given Pipeline Stage is used by this effect
         void clear(ShaderStage stage);               // Clear all additional code for given shader stage
         void clear(void);                              // Clear all additional code
         shared_ptr<Pipeline> pipeline(void);                  // Return pipeline object
         };

}
#endif

#endif
